apiVersion: v1
kind: Secret
metadata: 
 name: rabbitmq
 namespace: roboshop
 labels: 
    component: rabbitmq
    environment: dev
    tier: database
type: Opaque
data:
   RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
   RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="

---

apiVersion: v1
kind: Service
metadata: 
 name: rabbitmq-svc-headless
 namespace: roboshop
 labels: 
    component: rabbitmq
    environment: dev
    tier: database
spec:
 clusterIP: None
 selector:
  component: rabbitmq
  environment: dev
  tier: database
 ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672

---

apiVersion: v1
kind: Service
metadata: 
 name: rabbitmq
 namespace: roboshop
 labels: 
    component: rabbitmq
    environment: dev
    tier: database
spec:
 selector:
  component: rabbitmq
  environment: dev
  tier: database
 ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: rabbitmq
 namespace: roboshop
 labels: 
  component: rabbitmq
  environment: dev
  tier: database
spec:
 replicas: 2
 serviceName: "rabbitmq-svc-headless"
 selector:
  matchLabels:
    component: rabbitmq
    environment: dev
    tier: database
 template: 
  metadata: 
   labels: 
    component: rabbitmq
    environment: dev
    tier: database
  spec:
   containers:
    - name: rabbitmq
      image: rabbitmq:3 
      envFrom:
       - secretRef:
          name: rabbitmq 
      volumeMounts:
       - name: rabbitmq-vol
         mountPath: /var/lib/rabbitmq
 volumeClaimTemplates:
 - metadata:
   name: rabbitmq-vol
   spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs-sc"
        resources:
          requests:
            storage: 2Gi  
    
