apiVersion: v1
kind: Secret
metadata:
 name: mysql 
 namespace: roboshop
 labels:
  component: mysql
  environment: dev
  tier: database

type: Opaque
data:
 MYSQL_ROOT_PASS: "Um9ib1Nob3BAMQ=="

---

apiVersion: v1 
kind: Service
metadata:
 name: mysql-svc-headless
 namespace: roboshop
 labels:
  component: mysql
  environment: dev
  tier: database

spec:
 clusterIP: None 
 selector:
  component: mysql
  environment: dev
  tier: database
 ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1 
kind: Service
metadata:
 name: mysql
 namespace: roboshop
 labels:
  component: mysql
  environment: dev
  tier: database

spec:
 selector:
  component: mysql
  environment: dev
  tier: database
 ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mysql
 namespace: roboshop
 labels:
  component: mysql
  environment: dev
  tier: database

spec:
 replicas: 2
 serviceName: "mysql-svc-headless"
 selector:
  matchLabels:
    component: mysql
    environment: dev
    tier: database
 template:
  metadata:
   labels:
     component: mysql
     environment: dev
     tier: database

  spec: 
   containers:
    - name: mysql
      image: harshatejaadduri/mysql:v2
      envFrom:
       - secretRef:
          name: mysql
      volumeMounts:
       - name: mysql-vol
         mountPath: /var/lib/mysql     

 volumeClaimTemplates:
  metadata:
    name: mysql-vol
  spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "roboshop-ebs-sc"
        resources:
          requests:
            storage: 2Gi   


    