apiVersion: v1 
kind: ConfigMap
metadata:
 name: user
 namespace: roboshop
 labels:
  environment: dev
  component: user
  tier: backend  
data:
  REDIS_URL: 'redis://redis:6379' 
  MONGO_URL: "mongodb://mongodb:27017/users"
  MONGO: "true"
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: user
 namespace: roboshop
 labels:
  environment: dev
  component: user
  tier: backend
spec:  
 replicas: 1
 selector:
  matchLabels:
    environment: dev
    component: user
    tier: backend
 template:
  metadata:
   labels:
    environment: dev
    component: user
    tier: backend   
  spec: 
   containers:
    - name: user
      image: harshatejaadduri/user:v2
      envFrom:
       - configMapRef:
          name: user
      resource:
       requests:
        cpu: "50m"
        memory: "128Mi"
       limits:
        cpu: "100m"
        memory: "256Mi"  
--- 
apiVersion: v1 
kind: Service
metadata:
 name: user
 namespace: roboshop
 labels:
    environment: dev
    component: user
    tier: backend  
spec:
 selector:
    environment: dev
    component: user
    tier: backend
 ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
 name: user
 namespace: roboshop
spec: 
scaleTargetRef:
 apiVersion: apps/v1
 kind: Deployment
 name: user
minReplicas: 1
maxReplicas: 10
metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10

